---
- name: Install demostat dependencies
  apt:
    name: "{{ demostat_dependencies }}"
    state: present
    update_cache: "{{ demostat_apt_update }}"
    cache_valid_time: 3600

- name: Install sqlite3
  apt:
    name: "sqlite3"
    state: present
  when: demostat_db_engine == 'sqlite3'

- name: Install default-libmysqlclient-dev
  apt:
    name: default-libmysqlclient-dev
    state: present
  when: demostat_db_engine == 'mysql'

- name: Create group
  group:
    name: "{{ demostat_group }}"
    state: present

- name: Create user
  user:
    name: "{{ demostat_user }}"
    group: "{{ demostat_group }}"
    create_home: true
    home: "{{ demostat_path }}"

- include_tasks: pip.yml

- name: Create required directories
  file:
    state: directory
    owner: "{{ demostat_user }}"
    group: "{{ demostat_group }}"
    path: "{{ demostat_path }}/{{ item }}"
    mode: '750'
  with_items:
    - bin
    - var
    - var/logs

- include_tasks: config.yml

- name: Symlink logs directory
  file:
    src: "{{ demostat_path }}/var/logs"
    dest: '{{ demostat_path }}/logs'
    owner: "{{ demostat_user }}"
    group: "{{ demostat_group }}"
    state: link

- include_tasks: systemd.yml

- include_tasks: nginx.yml
  when: demostat_nginx_enabled
