---
- name: Install gunicorn.service
  template:
    src: "systemd/gunicorn.service.j2"
    dest: "/etc/systemd/system/{{ demostat_systemd_prefix }}gunicorn.service"
    mode: '644'
  notify:
    - systemd daemon reload
    - restart gunicorn
